//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.09.27 at 12:00:45 PM IST 
//


package edu.yaksha.salesapp;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the edu.yaksha.salesapp package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: edu.yaksha.salesapp
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link GetSalespersonRequest }
     * 
     */
    public GetSalespersonRequest createGetSalespersonRequest() {
        return new GetSalespersonRequest();
    }

    /**
     * Create an instance of {@link GetAllSalespersonRequest }
     * 
     */
    public GetAllSalespersonRequest createGetAllSalespersonRequest() {
        return new GetAllSalespersonRequest();
    }

    /**
     * Create an instance of {@link GetAllSalespersonResponse }
     * 
     */
    public GetAllSalespersonResponse createGetAllSalespersonResponse() {
        return new GetAllSalespersonResponse();
    }

    /**
     * Create an instance of {@link SalesPerson }
     * 
     */
    public SalesPerson createSalesPerson() {
        return new SalesPerson();
    }

    /**
     * Create an instance of {@link GetSalespersonResponse }
     * 
     */
    public GetSalespersonResponse createGetSalespersonResponse() {
        return new GetSalespersonResponse();
    }

}
