//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.09.27 at 12:00:45 PM IST 
//


package edu.yaksha.salesapp;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for SalesPerson complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SalesPerson">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="id" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="sales-value" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="commission-value" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SalesPerson", propOrder = {
    "id",
    "name",
    "salesValue",
    "commissionValue"
})
public class SalesPerson {

    protected int id;
    @XmlElement(required = true)
    protected String name;
    @XmlElement(name = "sales-value")
    protected double salesValue;
    @XmlElement(name = "commission-value")
    protected double commissionValue;

    /**
     * Gets the value of the id property.
     * 
     */
    public int getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     */
    public void setId(int value) {
        this.id = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the salesValue property.
     * 
     */
    public double getSalesValue() {
        return salesValue;
    }

    /**
     * Sets the value of the salesValue property.
     * 
     */
    public void setSalesValue(double value) {
        this.salesValue = value;
    }

    /**
     * Gets the value of the commissionValue property.
     * 
     */
    public double getCommissionValue() {
        return commissionValue;
    }

    /**
     * Sets the value of the commissionValue property.
     * 
     */
    public void setCommissionValue(double value) {
        this.commissionValue = value;
    }

}
